const URL_IMAGE_BASE = 'https://image.tmdb.org/t/p/';

export const imageConfig = {
  // Backdrop sizes
  URL_IMAGE_BACKDROP_w300: URL_IMAGE_BASE + 'w300',
  URL_IMAGE_BACKDROP_w780: URL_IMAGE_BASE + 'w780',
  URL_IMAGE_BACKDROP_w1280: URL_IMAGE_BASE + 'w1280',
  URL_IMAGE_BACKDROP_original: URL_IMAGE_BASE + 'original',

  // Poster sizes
  URL_IMAGE_POSTER_w92: URL_IMAGE_BASE + 'w92',
  URL_IMAGE_POSTER_w154: URL_IMAGE_BASE + 'w154',
  URL_IMAGE_POSTER_w185: URL_IMAGE_BASE + 'w185',
  URL_IMAGE_POSTER_w342: URL_IMAGE_BASE + 'w342',
  URL_IMAGE_POSTER_w500: URL_IMAGE_BASE + 'w500',
  URL_IMAGE_POSTER_w780: URL_IMAGE_BASE + 'w780',
  URL_IMAGE_POSTER_original: URL_IMAGE_BASE + 'original',

  // Logo sizes
  URL_IMAGE_LOGO_w45: URL_IMAGE_BASE + 'w45',
  URL_IMAGE_LOGO_w92: URL_IMAGE_BASE + 'w92',
  URL_IMAGE_LOGO_w154: URL_IMAGE_BASE + 'w154',
  URL_IMAGE_LOGO_w185: URL_IMAGE_BASE + 'w185',
  URL_IMAGE_LOGO_w300: URL_IMAGE_BASE + 'w300',
  URL_IMAGE_LOGO_w500: URL_IMAGE_BASE + 'w500',
  URL_IMAGE_LOGO_original: URL_IMAGE_BASE + 'original',

  // Profile sizes
  URL_IMAGE_PROFILE_w45: URL_IMAGE_BASE + 'w45',
  URL_IMAGE_PROFILE_w185: URL_IMAGE_BASE + 'w185',
  URL_IMAGE_PROFILE_h632: URL_IMAGE_BASE + 'h632',
  URL_IMAGE_PROFILE_original: URL_IMAGE_BASE + 'original',

  // Still sizes
  URL_IMAGE_STILL_w92: URL_IMAGE_BASE + 'w92',
  URL_IMAGE_STILL_w185: URL_IMAGE_BASE + 'w185',
  URL_IMAGE_STILL_w300: URL_IMAGE_BASE + 'w300',
  URL_IMAGE_STILL_original: URL_IMAGE_BASE + 'original'
};
